### ISSUE TITLE
Create different config files based on environment

### ISSUE THREAD

**Issue by nvonbulow** [communicode-source/communicode-api#3]
A fresh clone of this repository currently does not run without a copy of the `auth.json` config file. Rather than have `auth.json` ignored in `.gitconfig`, create multiple app profiles such as production, dev, etc. That way, you could have files such as `auth.dev.json` or `auth.production.json` that are used based on the `NODE_ENV` environment variable and add `auth.production.json` to `.gitignore`. See [here](http://stackoverflow.com/questions/16978256/what-is-node-env-in-express).

**Comment by trevorcrupi** [comment]
I like this.

**Comment by nvonbulow** [comment]
Testing GitHub Slack notifications.
